In [5]:
import numpy as np
a = np.eye(3, 4, k=0)
b = np.eye(3, 4, k=1)
c = 2 * a + b
print(c)
c.shape
c = c.reshape((12,1))
print(c)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]
[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [4]:
import numpy as np
import random
x = np.array(random.sample(range(1000),12))
print(x)
x = x.reshape((3,4))
print(x)
print(x.T)

[682 750 723   0 194 708 510 389  95 380  77 892]
[[682 750 723   0]
 [194 708 510 389]
 [ 95 380  77 892]]
[[682 194  95]
 [750 708 380]
 [723 510  77]
 [  0 389 892]]


In [11]:
import numpy as np
x = np.array([[1,1,1], [60,50,75]])
y = np.array([[10,7,12]])
x = x.T
y = y.T
#print(y)
b = ((np.linalg.inv(x.T.dot(x))).dot(x.T)).dot(y)
print(b)

[[-2.34210526]
 [ 0.19473684]]
